### ISSUE TITLE
coordinateUncertaintyInMeters valid range should be >0

### ISSUE THREAD

**Issue by ymgan** [iobis/obis-qc#36]
https://github.com/iobis/obis-qc/blob/37c0a0a9f8e51c0c8dbff0d86769475c3f475fbf/obisqc/location.py#L17C33-L17C33

Because [check_float](https://github.com/iobis/obis-qc/blob/37c0a0a9f8e51c0c8dbff0d86769475c3f475fbf/obisqc/util/misc.py#L13) uses `<=`, the minimum value for valid range should be 1 and not 0

Reasoning of why it should not be <1, please see this [comment](https://github.com/tdwg/bdq/issues/109#issuecomment-1449045995) which I agree

**Comment by pieterprovoost** [comment]
Valid range adjusted to correspond to BDQ.
